### ISSUE TITLE
The ability to get a resources image.

### ISSUE THREAD

**Issue by EazyFTW** [SpigotMC/XenforoResourceManagerAPI#15]
I think this could be a cool addition to the api.

**Comment by simpleauthority** [comment]
We won't add this to the API.

There is already enough information included in the response to create the image link yourself.

I'll add this to the README later. This is pseudocode.

For a given resource, in this case the one with ID 65668:
```
var resourceId = 65668;
var url = "https://www.spigotmc.org/data/resource_icons/";
url += format("%d/%d.jpg", floor(resourceId/1000), resourceId);
```

URL now contains:
https://www.spigotmc.org/data/resource_icons/65/65668.jpg

Which is valid for the resource:
![aalp icon](https://www.spigotmc.org/data/resource_icons/65/65668.jpg)

**Comment by Andre601** [comment]
Interesting solution, but there are some (major) issues.

1. When the resource doesn't have an icon set (uses the default icon) is the suggested method pointless because there's no icon under the generated URL.
2. You can't really see if the resource has a set icon or not, which makes it annoying to find out, if the URL would be valid or not.
